Feat replication group
schubergphilis/terraform-aws-mcaf-elasticache pull request #2
Opened 2021-04-19 16:27 UTC by lassebenni

2021-04-19 18:44 UTC, svanharmelen requested changes
Looks pretty good, but I still do have some remarks. All small things though...

2021-04-19 18:44 UTC, svanharmelen commented on variables.tf
> +  description = "The auth_token when using in-transit encryption"
Is this meant to be a required variable, or should it have a sane default instead? And can you place the new variable using alphabetical ordering?

2021-04-19 18:44 UTC, svanharmelen commented on variables.tf
> +  default     = false
Maybe default to `null`, which means you did not set the value. Seems like a good default since its an optional field.

2021-04-19 18:44 UTC, svanharmelen commented on variables.tf
> +  default     = false
Maybe default to `null`, which means you did not set the value. Seems like a good default since its an optional field.

2021-04-19 18:44 UTC, svanharmelen commented on variables.tf
> +  default     = []
Maybe default to null, which means you did not set the value. Seems like a good default since its an optional field.

2021-04-19 18:44 UTC, svanharmelen commented on output.tf
> +  value = var.replication_group ? aws_elasticache_replication_group.default[0].primary_endpoint_address : aws_elasticache_cluster.default[0].cache_nodes.*.address
Maybe this reads a bit easier:
```suggestion
  value = try(aws_elasticache_cluster.default[0].cache_nodes.*.address, aws_elasticache_replication_group.default[0].primary_endpoint_address)
```

2021-04-19 18:44 UTC, svanharmelen commented on output.tf
>  }
Fully agree that if something is an input, it should not be an output. But maybe this is now used in other configs, so I prefer to keep it in here.

2021-04-19 18:44 UTC, svanharmelen commented on output.tf
> +output "primary_endpoints" {
Why change the name? Think just keeping it `endpoints` will be better backwards compatible.

2021-04-19 18:44 UTC, svanharmelen commented on main.tf
> +  kms_key_id                    = var.at_rest_encryption ? var.kms_key_arn : null
This can just be like this if the default is `null`:
```suggestion
  kms_key_id                    = var.kms_key_arn
```

2021-04-19 18:44 UTC, svanharmelen commented on main.tf
> +  auth_token                    = var.in_transit_encryption ? var.auth_token : null
This can just be like this if the default is null:
```suggestion
  auth_token                    = var.auth_token
```

2021-04-19 18:44 UTC, svanharmelen commented on main.tf
> +  automatic_failover_enabled    = var.num_cache_nodes > 1 ? true : false
```suggestion
  automatic_failover_enabled    = var.num_cache_nodes > 1
```

2021-04-20 12:47 UTC, lassebenni commented
@svanharmelen Thanks for the feedback, I implemented your suggestions. Can you review again? = )

2021-04-20 13:35 UTC, merged

2021-04-20 15:00 UTC, svanharmelen commented
So you merged your own PR before an approval? Not the best practice if you ask me... I've setup branch protection rules to prevent that from happening again 😉